In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import pandas as pd
import numpy as np


**Step 2: Importing dataset**

In [ ]:
df = pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [ ]:
df.drop_duplicates(inplace = True)
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values
print(X)
print(Y)
df

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan, strategy = 'mean')     
imp.fit(X[:,1:3])
X[:, 1:3] = imp.transform(X[: , 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

**Step 4: Encoding categorical data**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Step 5: Creating a dummy variable**

In [ ]:
dummy1 = pd.get_dummies(df['Country'])
dummy1

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [ ]:
df = pd.concat([df,dummy1], axis=1)
df

Country   Age   Salary Purchased  France  Germany  Spain
0   France  44.0  72000.0        No       1        0      0
1    Spain  27.0  48000.0       Yes       0        0      1
2  Germany  30.0  54000.0        No       0        1      0
3    Spain  38.0  61000.0        No       0        0      1
4  Germany  40.0      NaN       Yes       0        1      0
5   France  35.0  58000.0       Yes       1        0      0
6    Spain   NaN  52000.0        No       0        0      1
7   France  48.0  79000.0       Yes       1        0      0
8  Germany  50.0  83000.0        No       0        1      0
9   France  37.0  67000.0       Yes       1        0      0

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
print(X_train)
print(y_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[1 1 1 0 1 0 0 1]


In [ ]:
print(X_test, y_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]] [0 0]


**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler    
sc = StandardScaler()
X[:,1:] = sc.fit_transform(X[:,1:])
X

array([[1.0, -0.6546536707079772, -0.6546536707079771, 0.758874361590019,
        0.7494732544921677],
       [0.0, -0.6546536707079772, 1.5275252316519463,
        -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.5275252316519468, -0.6546536707079771,
        -1.2755547779917342, -0.8912654918285229],
       [0.0, -0.6546536707079772, 1.5275252316519463,
        -0.1130238410878753, -0.253200423814921],
       [0.0, 1.5275252316519468, -0.6546536707079771,
        0.17760889313808945, 6.632191985654332e-16],
       [1.0, -0.6546536707079772, -0.6546536707079771,
        -0.5489729424268225, -0.5266568815350361],
       [0.0, -0.6546536707079772, 1.5275252316519463, 0.0,
        -1.0735697969752662],
       [1.0, -0.6546536707079772, -0.6546536707079771,
        1.3401398300419485, 1.3875383225057696],
       [0.0, 1.5275252316519468, -0.6546536707079771, 1.6307725642679132,
        1.7521469327992565],
       [1.0, -0.6546536707079772, -0.6546536707079771,
        -0.25834020